Pin Miniconda3 to a specific version
ContinuumIO/docker-images pull request #177
Opened 2020-07-31 13:56 UTC by damacus

The images are tagged with a Conda version so we should specify that version when we install it.
This also allows us to trigger a build based on changing the version

2020-10-28 15:15 UTC, damacus commented
Hey, what're the chances of getting this PR in? Or should we look at building our own from scratch?

2020-11-03 02:02 UTC, chenghlee requested changes

2020-11-03 02:02 UTC, chenghlee commented on miniconda3/debian/Dockerfile
> +ENV CONDA_VERSION=py38_4.8.3
Can we turn this into an `ARG`? That would make it easier to reuse this Dockerfile for other versions.

2020-11-03 09:45 UTC, damacus commented on miniconda3/debian/Dockerfile
> +ENV CONDA_VERSION=py38_4.8.3
I was just following precedence in https://github.com/ContinuumIO/docker-images/blob/master/miniconda3/alpine/Dockerfile#L52

2020-11-30 16:02 UTC, chenghlee approved these changes

2020-11-30 16:02 UTC, merged